project:
  type: book

book:
  title: "Some example Mathematical lecture notes"
  author: "Dr. A. Lecturer"
  chapters:
    - index.qmd
    - 01-determinant.qmd
    - 02-variance.qmd
    - references.qmd

bibliography: refs.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



